### ISSUE TITLE
Documentation + examples

### ISSUE THREAD

**Issue by bbsbb** [kirasystems/views-honeysql#7]
Hey guys,

I took a quick look at this and it seems interesting. I will spend the time to learn a bit more about the lib, but is there any chance of producing minimal documentation and/or examples? Thank you!

**Comment by ylebedeva** [comment]
Hi Boyan, sorry that you got no response at the time you've expected. It is nice to know that it looked interesting to you. We'll look into it anyway but cannot promise it to happen soon.
